# -*- coding: utf-8 -*-
mystr ='we are learning python'
#str = mystr.find("e")
#str = mystr.find("are",3 , 6)#注意是左闭右开区间
#str = mystr.index("we")
#str = mystr.count("e")
#str = mystr.replace("w", "W", mystr.count(str1))
#str = mystr.split(str=" ", 2)
#str = mystr.capitalize()
#str = mystr.title()
#str = mystr.startswith("we")
#str = mystr.endswith("we")
#str = mystr.lower()
#str = mystr.upper()
#str = mystr.ljust(30)
#str = mystr.rjust(30)
#str = mystr.center(30)
#str = mystr.lstrip()
#str = mystr.rstrip()
#str = mystr.strip()
#str = mystr.rfind("e")
#str = mystr.rindex("are")
#str = mystr.partition("are")
#str = mystr.rpartition("are")
#str = mystr.splitlines()
#str = mystr.isalpha()
#str = mystr.isdigit()
#str = mystr.isalnum()
#str = mystr.isspace()
#str = mystr.join(str)
print(str)